// File generated by Antigravity based on google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvQ0QtWRhLT4paKLo1ZFfW4t9lJgqr88',
    appId: '1:667500759230:android:26f01ee75ace71bf4df6ef',
    messagingSenderId: '667500759230',
    projectId: 'hr-pro-batra',
    storageBucket: 'hr-pro-batra.firebasestorage.app',
  );

  // ==========================================================================
  // ⚠️  iOS Firebase Configuration - يحتاج إعداداً حقيقياً قبل بناء نسخة iOS
  // ==========================================================================
  // معرّف التطبيق (appId) الحالي غير صحيح — يبدو نسخة معدّلة من appId الأندرويد
  // ولم يُنشأ تطبيق iOS في مشروع Firebase الفعلي بعد.
  //
  // خطوات التصحيح الصحيحة:
  //   1. افتح https://console.firebase.google.com/project/hr-pro-batra
  //   2. Project settings → Your apps → Add app → iOS
  //   3. Bundle ID: com.batra.hrpro.hrPro  (نفس الموجود في iosBundleId أدناه)
  //   4. حمّل ملف GoogleService-Info.plist وضعه في:
  //        mobile/ios/Runner/GoogleService-Info.plist
  //   5. أضفه من Xcode إلى Runner target (Drag → Copy items if needed).
  //   6. شغّل: `dart pub global run flutterfire_cli:flutterfire configure --project=hr-pro-batra`
  //      أو حدّث القيم أدناه يدوياً من الملف الجديد:
  //         - apiKey             ← API_KEY
  //         - appId              ← GOOGLE_APP_ID
  //         - iosBundleId        ← BUNDLE_ID
  //
  // حتى يُصحّح، أي محاولة تهيئة Firebase على iOS ستفشل صامتاً (لا FCM على iOS).
  // ==========================================================================
  // القيم تُمرَّر وقت البناء (CI أو محلياً) حتى لا تُحفظ في المستودع:
  //   flutter build ipa --dart-define=FIREBASE_IOS_APP_ID=1:667500759230:ios:xxxx   //                     --dart-define=FIREBASE_IOS_API_KEY=AIza...
  // بدونها يبقى appId بقيمة PLACEHOLDER فيتخطى main.dart تهيئة Firebase على iOS
  // (التذكيرات المحلية تعمل، إشعارات Push لا تعمل).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'AIzaSyBwvQ0QtWRhLT4paKLo1ZFfW4t9lJgqr88',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_IOS_APP_ID',
      defaultValue: 'PLACEHOLDER_IOS_APP_ID_REPLACE_BEFORE_BUILDING_IOS',
    ),
    messagingSenderId: '667500759230',
    projectId: 'hr-pro-batra',
    storageBucket: 'hr-pro-batra.firebasestorage.app',
    iosBundleId: 'com.batra.hrpro.hrPro',
  );
}
