// File generated by Antigravity based on google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvQ0QtWRhLT4paKLo1ZFfW4t9lJgqr88',
    appId: '1:667500759230:android:26f01ee75ace71bf4df6ef',
    messagingSenderId: '667500759230',
    projectId: 'hr-pro-batra',
    storageBucket: 'hr-pro-batra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvQ0QtWRhLT4paKLo1ZFfW4t9lJgqr88',
    appId: '1:667500759230:ios:76d4df6ef26f01ee75ace7', // تنبيه: يرجى تحديث هذا المعرف بمعرف تطبيق iOS الفعلي من لوحة تحكم Firebase إذا لزم الأمر
    messagingSenderId: '667500759230',
    projectId: 'hr-pro-batra',
    storageBucket: 'hr-pro-batra.firebasestorage.app',
    iosBundleId: 'com.batra.hrpro.hrPro',
  );
}
