name: Build iOS Simulator App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Build iOS Simulator App
        working-directory: ./mobile
        run: flutter build ios --simulator

      - name: Package Simulator App into IPA for Cloud Testing
        working-directory: ./mobile/build/ios/iphonesimulator
        run: |
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r HRBatra_Simulator.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HRBatra-iOS-Simulator-App
          path: mobile/build/ios/iphonesimulator/HRBatra_Simulator.ipa
